### ISSUE TITLE
Dz Rewiev lessons 5

### ISSUE THREAD

**Issue by andrewmarushko** [Sluchik/sluchik.github.io#4]
# НЕ ЗАЧЕТ

Зачем выносить одну логическую форму в три отдельные?

<img width="346" alt="screenshot 2015-11-13 13 52 43" src="https://cloud.githubusercontent.com/assets/4026421/11145587/93697b66-8a0f-11e5-8524-e19fde1137fd.png">
- [x] сделать все в одной форме;
- [x] сделать все кнопки кликабельны и при наведение на них должен быть cursor - poiner;
  для чего выносить каждый инпут в отдельный див?

<img width="363" alt="screenshot 2015-11-13 14 11 09" src="https://cloud.githubusercontent.com/assets/4026421/11145691/7a1b041c-8a10-11e5-8704-ff8a2bb7bc8a.png">
- [x] внести все инпуты в один див

**Comment by AndriiLitvin** [comment]
тут еще 
![image](https://cloud.githubusercontent.com/assets/13675947/14212585/549e27b0-f83c-11e5-87a4-d95212e3adca.png)
чтоб был зачет
